import Head from "next/head";
import Image from "next/image";
import { AiFillGithub, AiFillLinkedin, AiFillTwitterCircle } from 'react-icons/ai';
import { BsMoonStars } from 'react-icons/bs';
import sufian from "../public/sufian.jpg";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Abu Sufian</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons text-teal-500">sufian</h1>
            <ul className="flex items-center">
              <li><BsMoonStars className="cursor-pointer text-2xl text-cyan-500" /></li>
              <li className="capitalize">
                <a href="#" className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8">resume</a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium">Abu Sufian</h2>
            <h3 className="text-xl py-2">Web developer in React.</h3>
            <p className="text-md py-5 leading-8 text-gray-800">I am a web developer focused on React. If need react website join me down below and let's get cracking!</p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
            <AiFillLinkedin />
            <AiFillGithub />
            <AiFillTwitterCircle />
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden border-4 border-cyan-600">
            <Image src={sufian} alt="sufian" objectFit="cover" />
          </div>
        </section>
      </main>
    </div>
  );
}
