import Head from "next/head";
import { BsMoonStars } from 'react-icons/bs';


export default function Home() {
  return (
    <div>
      <Head>
        <title>Abu Sufian</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons text-teal-500">sufian</h1>
            <ul className="flex items-center">
              <li><BsMoonStars className="cursor-pointer text-2xl text-cyan-500" /></li>
              <li className="capitalize">
                <a href="#" className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8">resume</a>
              </li>
            </ul>
          </nav>
          <div>
            <h2>Abu Sufian</h2>
            <h3>Web developer in React</h3>
          </div>
        </section>
      </main>
    </div>
  );
}
